# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ce51a56fcc08d677c7c7a601b1a7b27ebdda1dec6e7d3c81b437e0047415433bdd8c5047474d8e0eb7dad2a7f13cc43b95bfa81e098cdaad8231368d7434fce

test:
  secret_key_base: c017cd3ae0784e5a668f09ac1215875eb849b8f47c3840a8c747ae3a1658b3b3fce07176677f86a1ad57266d928c01840b6d52ee78b117f87b3b658d5a1448b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
