Product.create!([
  {name: "Pepperoni Pizza", price: "2.0", image: "http://www.cicis.com/media/1138/pizza_trad_pepperoni.png", description: "Yummy Pizza", stock: true},
  {name: "iPad", price: "600.0", image: "https://support.apple.com/content/dam/edam/applecare/images/en_US/ipad/featured-content-ipad-icon_2x.png", description: "electronic tablet", stock: true},
  {name: "Cheesecake", price: "4.0", image: "https://files.graphiq.com/5806/media/images/t2/Jack_in_the_Box_New_York_Style_Cheesecake_7486133.png", description: "Cake Cake Cake Cake *Rihanna Voice*", stock: true},
  {name: "Sleek Concrete Bottle", price: "47.0", image: "https://robohash.org/doloremundenobis.png?size=300x300&set=set1", description: "Electronics & Bath", stock: true},
  {name: "Synergistic Paper Shoes", price: "50.0", image: "https://robohash.org/voluptasestlaboriosam.png?size=300x300&set=set1", description: "We need to index the wireless FTP program!", stock: true},
  {name: "Ice Cream", price: "2.0", image: "http://orig01.deviantart.net/b0cb/f/2010/004/5/8/ice_cream_transparent_png_by_absurdwordpreferred.png", description: "Strawberry Flavored", stock: true},
  {name: "Hot Dog", price: "1.0", image: "http://pngimg.com/upload/hot_dog_PNG10231.png", description: "Yummy dog", stock: true},
  {name: "Jameson", price: "45.0", image: "http://liquiddrops.co.uk/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/j/a/jameson_irish_whiskey.png", description: "Alcohol for after a long day ", stock: true},
  {name: "Wine", price: "25.0", image: "http://pngimg.com/upload/wineglass_PNG2863.png", description: "Best drink ever", stock: true},
  {name: "iphone", price: "450.0", image: "http://pngimg.com/upload/iphone_PNG5740.png", description: "phone", stock: true},
  {name: "Champagne", price: "202.0", image: "http://www.pngall.com/wp-content/uploads/2016/05/Champagne-PNG-Picture.png", description: "Its a champagne campaign", stock: true},
  {name: "Sareena Heel", price: "80.0", image: "http://myfashionwants.com/wp-content/uploads/2012/10/Valentino-Pink-Patent-Leather-Platform-Pumps.png", description: "Pink pumps", stock: true},
  {name: "Burger", price: "5.0", image: "http://pngimg.com/upload/burger_sandwich_PNG4133.png", description: "Yummy Burger", stock: true},
  {name: "Taco", price: "10.0", image: "http://66.media.tumblr.com/b426d3dd7fb8ca2f935bf885faff9f7b/tumblr_mndie22zrq1s56exfo1_500.png", description: "Aint no party like a taco party ", stock: true},
  {name: "BUrrito", price: "1.5", image: "http://www.tacobueno.com/media/1381/beefbob.png?quality=65", description: "Beefy Burrito", stock: true},
  {name: "Blue Jeans", price: "50.0", image: "http://freepngimages.com/wp-content/uploads/2015/12/light-blue-denim-jeans-transparent-image.png", description: "Blue Jeans", stock: true},
  {name: "Beanie", price: "25.0", image: "http://dissfeld.com/wordpress/wp-content/uploads/2015/01/Beanie-Gray_1200.png", description: "Grey Beanie", stock: true},
  {name: "Chicken Nuggets", price: "4.0", image: "http://67.media.tumblr.com/7e9561a84cabd2c1afbd259e9cbb9b8d/tumblr_mj1z6dqyu71rgpyeqo1_400.png", description: "With Your Favorite Sauce", stock: false}
])
